Week4 homework Abdulrahman sadek
HackYourHomework/Homework-class34 pull request #26
Opened 2021-10-26 17:26 UTC by Abdulrahmansadek

2021-11-02 19:40 UTC, killoncio commented on 1-JavaScript/Week4/homework/ex1-doubleEvenNumbers.test.js
> +  const newNumbers = numbers
Well done!

2021-11-02 19:42 UTC, killoncio commented on 1-JavaScript/Week4/homework/ex2-mondaysWorth.test.js
> +function computeEarnings(tasks, rate) {
Well done!
I'd suggest to use even more descriptive names for the variables. Can you rethink `monday` and `calculateRate` variable names so they reflect better what they are storing?

2021-11-02 19:43 UTC, killoncio commented on 1-JavaScript/Week4/homework/ex3-lemonAllergy.test.js
>      // TODO replace next line with your code
I think the tests are missing, you also have to make them work.

2021-11-02 19:43 UTC, killoncio commented on 1-JavaScript/Week4/homework/ex4-observable/ex4-observable.js
> +      subscribers.push(subscriber);
Well done!

2021-11-02 19:45 UTC, killoncio commented on 1-JavaScript/Week4/homework/ex5-wallet/index.js
> +      `Transferring ${eurosFormatter.format(
Well done!

2021-11-03 14:47 UTC, Abdulrahmansadek commented on 1-JavaScript/Week4/homework/ex3-lemonAllergy.test.js
>      // TODO replace next line with your code
Hey @killoncio thanks for reviewing my homework i will work on the test.

2021-11-14 14:12 UTC, robvk commented on 1-JavaScript/Week4/homework/ex3-lemonAllergy.test.js
>      // TODO replace next line with your code
Hi @Abdulrahmansadek , looks like you haven't done this yet?

2021-11-14 15:00 UTC, Abdulrahmansadek commented on 1-JavaScript/Week4/homework/ex3-lemonAllergy.test.js
>      // TODO replace next line with your code
hi @robvk  yes im will be sure to get them done by today . sorry I was so busy with the project .

2021-11-14 15:38 UTC, Abdulrahmansadek reviewed
@robvk  here also resolving the issue of the fruits basket ex.

2021-11-15 12:44 UTC, robvk requested changes
Not yet, you made a mistake with the should not modify check

2021-11-15 12:44 UTC, robvk commented on 1-JavaScript/Week4/homework/ex3-lemonAllergy.test.js
> +    expect(originalFruitBasketContents).toBe(fruitBasket);
Does this do the ```should not modify the original `fruitBasket` array``` check?

2021-11-16 08:52 UTC, Abdulrahmansadek reviewed
hi @robvk  I think now is working well .

2021-11-22 09:35 UTC, closed without merging