Homework week 1 ChrisFayad
HackYourHomework/Homework-class34 pull request #29
Opened 2021-11-01 15:35 UTC by ChrisFayad

2021-11-03 16:28 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +  const ul = document.createElement('ul');
Great start ;-)

2021-11-03 16:29 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +  ul.style.width = 'calc(100% - 41px)';
You have a lot of lines for changing styling. Can you think of a more succinct way where you need to do only one assignment to `ul.style` ?

2021-11-03 16:58 UTC, wilgert requested changes
You did very well, great job!
Only ex5-catWalk is not working and needs fixing.
I've added some questions and suggestions to help you learn on the exercises.

2021-11-03 16:58 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +    const li = ul.appendChild(document.createElement('li'));
Nice trick, that you use the fact that `appendChild` returns the element. Unfortunately you incur a small performance penalty. Because every modification you do on the `li` when it's added to the DOM will cause a rerender.
Whereas when you would first set all the properties of the `li` and add it to the DOM at the end it will only cause one rerender.
For a small exercise like this one that is not really an issue, but if you create a big application it can add up and make your app slower than necessary.

2021-11-03 16:58 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +    if (book.title === "The Design of Everyday Things") {
What would happen if we now get a new list, containing twenty books?
Can you think of a way to make this code more scalable.

(Hint: you can use the isbn to link the book to its image)

2021-11-03 16:58 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
>  const ulElement = createBookList(myBooks);
The result looks really good, great job! :-)

2021-11-03 16:58 UTC, wilgert commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +Array.from(listElements).forEach( listElement => {
Looks good, do you know an alternative to `Array.from` to turn the `listElements` into an `Array`?

2021-11-03 16:58 UTC, wilgert commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +    console.log(time);
Please be careful, and remove `console.log` before submitting homework!

2021-11-03 16:58 UTC, wilgert commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +    const time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
This was a good practice in string concatenation. I will teach you a trick: `today.toLocaleTimeString()` will give you the same result in one go!
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString

2021-11-03 16:58 UTC, wilgert commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +  setInterval(catInterval, 15000);
Hmm, I guess you have spend quite some time on this. Unfortunately it is not working correctly yet. I also think that you should not need 3  `setInterval` calls to get this working. You should have one `setInterval` for walking and one `setTimeout` for dancing.

2021-11-03 16:58 UTC, wilgert commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +      if (imgElement.style.left === `${windowWidth / 2}px`) {
On my screen the cat is not stopping in the middle because the cat is taking 10px steps and this.
So if your screen is for example 768 pixels wide the middle will be 384, which will never be the value of `style.left`.

2021-11-03 16:58 UTC, wilgert commented on 2-Browsers/Week1/homework/ex3-hijackLogo.js
> +   const googleLogo = document.getElementsByClassName('lnXdpd')[0];
While this works I would recommend not using the className as a matcher. As this className looks autogenerated it might change in the future. A better matcher would be the `alt` attribute. You can match it by using `document.querySelector('[alt="Google"]')`.

2021-11-04 20:14 UTC, ChrisFayad commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +Array.from(listElements).forEach( listElement => {
I can do it by using the **Spread Operator** ```[...listElements].forEach()```

2021-11-04 20:18 UTC, ChrisFayad commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +    console.log(time);
The only reason I used the _console.log_ here is because it's mentioned on the **Homework Browsers Week 1** README file 

> Verify that the current time is displayed correctly on both the web page and the browser's console.

2021-11-04 20:22 UTC, ChrisFayad commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +    const time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
Thanks for the info &#128077;

2021-11-04 20:24 UTC, ChrisFayad commented on 2-Browsers/Week1/homework/ex3-hijackLogo.js
> +   const googleLogo = document.getElementsByClassName('lnXdpd')[0];
Very Useful &#128515;

2021-11-05 10:56 UTC, wilgert commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +    console.log(time);
Ah, I missed that it's in the instructions.

2021-11-05 11:18 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +      case '978-0465050659':
This is a good improvement on what you previously had. I would solve it a bit different still. I would create an object that holds the link between isbn and image like this:

```
const bookImages = {
    '978-0465050659': {
        src: 'assets/the_design_of_everyday_things.jpg',
        alt: 'The Design of Everyday Things Cover',
    },
    '978-1617933431': {
        src: 'assets/the_most_human_human.jpg',
        alt: 'The Most Human Human Cover',
    },
    '978-0201616224': {
        src: 'assets/the_pragmatic_programmer.jpg',
        alt: 'The Pragmatic Programmer Cover',
    },
};

const bookImage = bookImages[book.isbn];
if(bookImage) {
    img.setAttribute('src', bookImage['src']);
    img.setAttribute('alt', bookImage['alt']);
}
```

2021-11-05 11:30 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +  ul.style.width = 'calc(100% - 41px)';
I've learned something here as I was under the impression that you could just assign an object to `element.style` like this:

```
    li.style = {
      width: 'calc(25% - 51px)',
      margin: '15px',
      padding: '10px',
      minWidth: '350px',
    };
```

But that does not work.
After Googling I found this answer on [StackOverflow](https://stackoverflow.com/a/31255093/357601) which suggest using a function like this:

```
function setStyle(el, propertyObject) {
    for (var property in propertyObject) {
        el.style[property] = propertyObject[property];
    }
}

li.setStyle({
      width: 'calc(25% - 51px)',
      margin: '15px',
      padding: '10px',
      minWidth: '350px',
});
```

2021-11-05 11:37 UTC, ChrisFayad commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +  ul.style.width = 'calc(100% - 41px)';
It will not work if you don't add _**.cssText**_ after **li.style** .. I don't think the solution you found on _StackOverflow_ is needed &#128556;

2021-11-05 11:54 UTC, wilgert approved these changes
Great job implementing my suggestions!

2021-11-05 11:54 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +    ul.appendChild(li);
The performance improvement comes when this line all the way at the bottom of the loop. So after you have set all the properties on the `li` you add it to the DOM by doing `appendChild`.

2021-11-05 11:54 UTC, wilgert commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +      if (imgElement.style.left === `${windowWidth / 2}px`) {
I see that you did not manage to solve this.
I will start the lesson on sunday by showing an example of a working version.

2021-11-05 11:56 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +  ul.style.width = 'calc(100% - 41px)';
The downside of using `.cssText` is that now your styling is inside a string. And your code editor can not prevent you making mistakes like forgetting a `'` or  `: `.
Still I think the best solution is to put all the styling in a class in a css file and apply that class in JavaScript!

2021-11-14 09:25 UTC, closed without merging