Browser week 1
HackYourHomework/Homework-class34 pull request #31
Opened 2021-11-02 10:31 UTC by Danielboi886

This is my assignment for Browser week 1

2021-11-03 17:46 UTC, wilgert requested changes
Hi Daniel , great job handing in the homework so quickly!
Unfortunately there are two things that need to be fixed before I can review it:
1. Please install and run Prettier and commit the now nicely formatted code! See: https://github.com/HackYourFuture/Homework#install-recommended-vscode-extensions for an explanation how you do this.

2. Please make sure all of the tests pass. Right now only ex4 passes. See the test-reports folder.

2021-11-04 11:23 UTC, Danielboi886 commented
> Hi Daniel , great job handing in the homework so quickly! Unfortunately there are two things that need to be fixed before I can review it:
> 
> 1. Please install and run Prettier and commit the now nicely formatted code! See: https://github.com/HackYourFuture/Homework#install-recommended-vscode-extensions for an explanation how you do this.
> 2. Please make sure all of the tests pass. Right now only ex4 passes. See the test-reports folder.

Hi Wilgert, 

I've fixed the format and run all the tests! 

for ex5 I did pass all the tests but I'm unsure about changing the cat GIF to the dancing one and the code seems alright but didn't do as what is expected in the browser.

2021-11-06 13:51 UTC, wilgert requested changes
You did quite well, some small improvements can be made. 
Except for the Catwalk, that one is not working on my computer.

2021-11-06 13:51 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
>  function createBookList(books) {
Your booklist looks nice :-)

2021-11-06 13:51 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +  const imgRepo = [
Do you think it is a robust solution to use the order of the books to determine the picture?
What would happen if a book is added to the start of the list?

A more bulletproof solution would be using the `isbn` to look up the right image in an object.

Something like this:

const bookImages = {
    '978-0465050659': {
        src: 'assets/the_design_of_everyday_things.jpg',
        alt: 'The Design of Everyday Things Cover',
    },
    '978-1617933431': {
        src: 'assets/the_most_human_human.jpg',
        alt: 'The Most Human Human Cover',
    },
    '978-0201616224': {
        src: 'assets/the_pragmatic_programmer.jpg',
        alt: 'The Pragmatic Programmer Cover',
    },
};

const bookImage = bookImages[book.isbn];
if(bookImage) {
    image.src = bookImage['src'];
    image.alt = bookImage['alt'];
}

2021-11-06 13:51 UTC, wilgert commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +    ul.appendChild(li);
It's best to delay adding the element to the DOM until you have finished changing its properties. So I would move it all the way to the bottom of the loop after `li.style.padding = '20px';`

2021-11-06 13:51 UTC, wilgert commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +}
nice work!

2021-11-06 13:51 UTC, wilgert commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +  }, 1000);
Looks nice!

2021-11-06 13:51 UTC, wilgert commented on 2-Browsers/Week1/homework/ex3-hijackLogo.js
> +  const logo = document.getElementsByClassName('lnXdpd');
I would not use this class as the selector. It looks like it is automatically generated and it might change the next time Google does an update.
I think it's better to select by the `alt=Google` attribute like this: `document.querySelector('[alt="Google"]')`

2021-11-06 13:51 UTC, wilgert commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
>  function catWalk() {
The cat is not behaving like it should on my computer.
Is it working on yours?

2021-11-14 14:24 UTC, robvk commented
@Danielboi886, please have a look at the last problems mentioned

2021-11-22 14:56 UTC, closed without merging