Homework Browsers/week 1 Caglar
HackYourHomework/Homework-class34 pull request #35
Opened 2021-11-02 13:15 UTC by caglar-kaya

2021-11-03 17:57 UTC, wilgert requested changes
You did well. Some small improvements possible on most exercises.
Unfortunately ex5-catWalk is not completely working yet, see comment in that file.

2021-11-03 17:57 UTC, wilgert commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +const clock = document.createElement('div');
The idea of using `DOMContentLoaded` is that you do not start to access/modify the DOM until it finished loading.
By putting this code outside the `addCurrentTime` function you are actually changing the DOM too early.

Can you come up with a design that does not have this issue? Be warned: do not make the common mistake of calling `setInterval` multiple times ;-)

2021-11-03 17:57 UTC, wilgert commented on 2-Browsers/Week1/homework/ex3-hijackLogo.js
> +  const googleLogo = document.querySelector('img[alt="Google"]');
Great job!

2021-11-03 17:57 UTC, wilgert commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +const mover = setInterval(catWalk, 50);
Your code looks quite nice. Unfortunately your cat gets stuck in the middle of the screen after dancing.
Can you make it move until the end of the screen, and start again at the begin as described in points 5 and 6?

2021-11-04 11:40 UTC, caglar-kaya commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +const clock = document.createElement('div');
Hey @wilgert,
First of all, thank you so much for your review my homework and your comments..
I got what you mean. I'll fix this bug as soon as possible..

2021-11-04 11:41 UTC, caglar-kaya commented on 2-Browsers/Week1/homework/ex3-hijackLogo.js
> +  const googleLogo = document.querySelector('img[alt="Google"]');
Thanks you @wilgert .. :)

2021-11-04 12:00 UTC, caglar-kaya commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +const mover = setInterval(catWalk, 50);
I have tried and also searched on google to make my cat move until the end of the screen but unfortunately I am stuck also like my cat..But I'll rethink about it..

2021-11-05 14:00 UTC, caglar-kaya commented
Hi @wilgert ,
I have updated ex4 and ex5..I have inspired from Alex's code on Slack for ex4 and also I'm not fully satisfied with ex5.

2021-11-06 13:59 UTC, wilgert commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +  const addCurrentTime = () => {
I would not use the same name as the outer function. It's not clear which one will be called on line 30.

2021-11-06 14:03 UTC, wilgert commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +      setTimeout(() => { move += 10 }, 5000);
How many times do you think this `setTimeout` is called?

2021-11-06 18:17 UTC, caglar-kaya commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +  const addCurrentTime = () => {
I didn't realise that the names were same. Now I changed inner one as `addUpdatedTime`.

2021-11-06 18:34 UTC, caglar-kaya commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +      setTimeout(() => { move += 10 }, 5000);
I did like this:
```
      setTimeout(() => { move += 10; }, 5000);
      counter++;
      console.log(counter);
```
and result was 131 on the console.

2021-11-14 14:30 UTC, robvk commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +      setTimeout(() => { move += 10 }, 5000);
@caglar-kaya , that's a little much, should only be called once. Maybe you can think of a way to check if you have already set this in motion and then not do this part?

2021-11-14 19:53 UTC, caglar-kaya commented
Hello @robvk 
I have edited setTimeout function and some conditions.

2021-11-15 12:47 UTC, closed without merging