homework week1 browser Abdulrahman sadek
HackYourHomework/Homework-class34 pull request #36
Opened 2021-11-02 17:31 UTC by Abdulrahmansadek

2021-11-06 10:10 UTC, cgduncan7 requested changes
Really nice work @Abdulrahmansadek 👏 

There are a few minor things I'd like to see changed though.

1. you are so close to all tests passing! Try to solve the minor issues
2. ex2 for-loop needs a revisit
3. ex4 time-string formatting needs a revisit

Once you do these it'll be 💯 👌

2021-11-06 10:10 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex3-hijackLogo.js
> +  const googleImage = document.getElementById('hplogo_new');
well done 👏

2021-11-06 10:10 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
>  // TODO execute `addCurrentTime` when the browser has completed loading the page
This `TODO` comment caused your tests to fail! Don't forget the clean-up 😄

2021-11-06 10:10 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +  }
Hmm... I think there are some mistakes here. Let's take a look at an example.

Suppose the values of `hours`, `minutes`, and `seconds` are as defined below:
```javascript
hours = 1;
minutes = 1;
seconds = 1;
```

What will you write to the `div`? `seconds` is indeed less than 10 so the first `if-statement` will be true and we will have
```javascript
div.textContent = "1:1:01"
```
This doesn't look like a proper _HH:MM:SS_ time to me 😄

Try to rewrite this to solve this problem

2021-11-06 10:10 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +      left += 10;
```suggestion
    } else if (left >= windowWidth - 10 && left <= windowWidth) {
      //reset the left at the end
      left = 0;
    } else {
      //normal situation
      left += 10;
```

Make sure the comments are in the correct block of code!

2021-11-06 10:10 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
>  // TODO execute `catWalk` when the browser has completed loading the page
Nasty `TODO` failing your tests again 👿

2021-11-06 10:10 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +  let walk = setInterval(walkBreakPoints, 50);
😹 👍

2021-11-07 10:15 UTC, Abdulrahmansadek commented
hey, @cgduncan7 thanks a lot for reviewing my homework I'm gonna go through the comments. thanks a lot again.

2021-11-14 14:31 UTC, robvk commented
@Abdulrahmansadek , please have a look at this. It is still open.

2021-11-14 15:27 UTC, Abdulrahmansadek reviewed
@robvk  this is the my modified homework and all the problems are solved .

2021-11-15 12:51 UTC, closed without merging