Week1-Browser-Osama Bazbooz
HackYourHomework/Homework-class34 pull request #38
Opened 2021-11-02 19:33 UTC by obazbooz

2021-11-06 10:39 UTC, cgduncan7 requested changes
Great work @obazbooz 👏 Everything is working but there are some issues with ex4 and ex5. Please take a look at my comments and see if you can address them 👍

2021-11-06 10:39 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +      imgEl.alt = 'Image Not Found!';
This line is being used regardless of the value of `index`... it probably doesn't belong in this `if-statement` then

2021-11-06 10:39 UTC, cgduncan7 commented on test-runner.log
> +
Woohoooooo! All tests passed! 💯 🍻

2021-11-06 10:39 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +  const ulEl = document.createElement('ul');
```suggestion
  const ulElement = document.createElement('ul');
```

Don't be afraid to have long variable names.. It's much more readable 😃

2021-11-06 10:39 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +spanElHomeTown.replaceWith(pElHome);
You don't need to literally replace the `span`. Could just change the text of the `span` but this works.

2021-11-06 10:39 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +liEl.forEach((element) => element.classList.add('list-item'));
This is arranged in a very confusing manner. Adding some line breaks between different logically grouped parts of your code along with comments will greatly improve readability

2021-11-06 10:39 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +pElFood.textContent = 'Sushi';
🍣 me too

2021-11-06 10:39 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex3-hijackLogo.js
> +  const logoEl = document.getElementsByClassName('lnXdpd')[0];
🕵️

2021-11-06 10:39 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +  divEl.textContent = `The current time is: (H:${timeEl.getHours()} M:${timeEl.getMinutes()} S:${timeEl.getSeconds()} )`;
This isn't what was meant by `HH:MM:SS` format. Output the text like you would expect to see on a digital clock!
For example: 
> 12:34:56

2021-11-06 10:39 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +  else if (steps === 400) {
What if my screen width is `100000`? `400` won't be halfway... How can you make sure that it always occurs at the halfway point?

2021-11-06 10:39 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +  }
This function is unused

2021-11-14 14:32 UTC, robvk commented
@obazbooz , please have a look at the comments

2021-11-22 14:16 UTC, closed without merging