browsers-w1-homework
HackYourHomework/Homework-class34 pull request #40
Opened 2021-11-03 09:50 UTC by SaidYein

2021-11-06 10:51 UTC, cgduncan7 requested changes
Really nicely done. Comments and code organization are great 👍 

Take a look at ex2, you forgot one step and did one step incorrectly!

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +    //add some style (doing style here just for practicing DOM. Otherwise, I would create style tag in HTML or do the styling in CSS file)
👍

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +  function renderProductList(item) {
You can have this function defined outside of `createBookList` function

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +ulElement.children[0].appendChild(img_1);
This should probably be done within `renderProductList`.

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +img_1.setAttribute('alt', 'book cover')
If the `alt` is always the same why not make a reusable function to create your custom `img` elements and then use that?

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +img_1.setAttribute('alt', 'book cover')
Also, adding to DOM after it has been rendered will be a bit costly. This solution also only works for 3 books!

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +  list[i].textContent = aboutMe[i];
You need to change the content of the `span` within this `li`. Not the `li` itself.

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +document.body.style.fontFamily = 'Arial, sans-serif';
You forgot to do step 4!

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +  list[i].setAttribute('class', 'list-item');
👍

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +  const dateTime = currentDate.toLocaleTimeString();
👏 don't reinvent the wheel 😆

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +//PS: this is my second version. I did HH:MM:SS format with function manually without using 'toLocaleTimeString()' in the first version. I like that one better but this is cleaner :)
👍

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +const walkingCat = 'http://www.anniemation.com/clip_art/images/cat-walk.gif';
well done having a `const`-section. Makes it easier to reuse these variables throughout your code

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +  if (step === halfway - (halfway % 10)) {
Smart way to make sure that `halfway` is always reached!

2021-11-06 10:51 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +  //I have designed the action in to three parts: before halfway, halfway and after halfway, So below will call 'step function after and before halfway'
Nice clean code 👍

2021-11-06 10:53 UTC, cgduncan7 commented
Also, you can include your unit-test reports as well 😄

2021-11-09 10:23 UTC, SaidYein commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
I am not sure if I was allowed to change myBooks object but I needed indexes and could not do what I wanted without changing the object.

2021-11-09 19:21 UTC, cgduncan7 approved these changes
Much better, nice improvements @SaidYein 👏

2021-11-09 19:21 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +function createImageElement(index) {
Nice 💯

2021-11-14 09:25 UTC, closed without merging