Finish w1-Browser homework
HackYourHomework/Homework-class34 pull request #43
Opened 2021-11-03 16:35 UTC by george2621

2021-11-03 16:38 UTC, george2621 commented
George Roumieh, I pushed my homework on Monday but I canceled The first PR because It was wrong

2021-11-09 19:43 UTC, cgduncan7 requested changes
Looks good but try to format the time correctly for ex4 😄 

It's a small change but still important!

2021-11-09 19:43 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +    bookImg.alt = 'Book cover';
Try to give this `alt` more purpose. A better value would be the title of the book!

2021-11-09 19:43 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +    const bookImg = document.createElement('img');
Nice var names 👏

2021-11-09 19:43 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +document.body.style.fontFamily = 'Arial, sans-serif';
Perfect 🆗

2021-11-09 19:43 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +    today.getHours() + ':' + today.getMinutes() + ':' + today.getSeconds();
Hmm... I don't think this will end up being formatted correctly! You could have `1:1:1` which is a strange way to read the time 😄

2021-11-09 19:43 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +}
Nice reusable and clear code 👏

2021-11-09 19:43 UTC, cgduncan7 commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +  catImg.style.left = parseFloat(catImg.style.left) + 10 + 'px';
🐱 🕺

2021-11-14 14:33 UTC, robvk commented
@george2621 , please have a look at the comments

2021-11-14 14:45 UTC, george2621 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +    bookImg.alt = 'Book cover';
> @george2621 , please have a look at the comments

I will check now, I am sorry about the delay but we had a hard week, thank Rob for the review and reminding

2021-11-14 14:47 UTC, george2621 commented on 2-Browsers/Week1/homework/ex1-bookList/index.js
> +    bookImg.alt = 'Book cover';
Thanks, @cgduncan7  I will fix it asap

2021-11-14 14:48 UTC, george2621 commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +    today.getHours() + ':' + today.getMinutes() + ':' + today.getSeconds();
@cgduncan7  you mean it should be 01:01:01 ??

2021-11-14 15:06 UTC, george2621 reviewed
fixed my homework @cgduncan7

2021-11-22 14:03 UTC, closed without merging