week1-homework-API
HackYourHomework/Homework-class34 pull request #49
Opened 2021-11-21 20:49 UTC by Abdulrahmansadek

2021-11-25 11:15 UTC, jontra000 requested changes
Hi @Abdulrahmansadek, two issues to address before I can approve this.

- There is a bug in ex2
- You still need to add the explanations for ex3 and ex4 as requested at the end of the homework questions

Other than that, the code looks good!

2021-11-25 11:15 UTC, jontra000 commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +function checkDoubleDigits(numbers) {
This function fails with the error message `Error(...) is not a constructor` when called with a value outside the range.

2021-11-25 14:16 UTC, Abdulrahmansadek reviewed
@jontra000  thanks a lot for reviewing my code 
I fixed it now should be fine I think 
or ex2 the message it was out of the parentheses () 😣.
and I add explanation or ex3 and ex4

2021-11-26 12:19 UTC, jontra000 approved these changes
Great! All looks good now.

2021-11-30 13:24 UTC, closed without merging