George roumieh-w1-usingAPI
HackYourHomework/Homework-class34 pull request #50
Opened 2021-11-22 09:32 UTC by george2621

2021-11-25 12:38 UTC, jontra000 requested changes
Hi @george2621, the code all looks good and works. Nice work there. However you still need to add your explanations for the behaviour in ex3 and ex4 as requested in the homework questions before I can close as approved

2021-11-25 12:38 UTC, jontra000 commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +      resolve(fullName);
Style note: Best practise is to move the declaration of fullName here. Keeping the declaration of variables as close as possible to where they are used makes the code cleaner and easier to understand, and reduces the chances of introducing bugs.

2021-11-25 12:38 UTC, jontra000 commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> -// ! Do not change or remove the code below
The unit tests are failing because these lines have been removed

2021-11-25 12:41 UTC, george2621 commented
@jontra000 Thanks, I will fix it asap

2021-11-27 15:49 UTC, george2621 commented
@jontra000 I fixed all issues but when I  try to make re-request isn't working

2021-11-27 18:38 UTC, jontra000 approved these changes
Thanks @george2621. All looks good now

2021-11-27 18:39 UTC, george2621 commented
Thanks  for reviewing and advising @jontra000

2021-11-27 18:50 UTC, george2621 commented
@can you approve it now ? or does it needs more modification?

2021-11-27 18:55 UTC, jontra000 commented
No more modifications needed. I'm still waiting for write permissions on the repo to approve it but I will as soon as I get them.

2021-11-30 13:25 UTC, closed without merging