Homework usingAPIs-week1 SaidYein
HackYourHomework/Homework-class34 pull request #51
Opened 2021-11-22 12:08 UTC by SaidYein

2021-11-25 15:11 UTC, remarcmij requested changes
Hi @SaidYein, the exercises are mostly correct but there are some issues I would like you to look at. 

Also, please include all the test reports in your pull request.

2021-11-25 15:11 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +            return;
In general, it is a good practice to add `return` statement here. However, in this exercise, the instructions say that the die should complete its scheduled rolls even after rolling off the table. So please remove this `return` and then explain in a comment why the promise that is rejected at this point does not become resolved when the die has completed its scheduled roll (i.e. when ultimately `resolve` is called).

2021-11-25 15:11 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +// Promise.all waits for the promise that take the longest time to be fulfilled. Thus, in case of rejection, rejected dies are still rolling until finishing their assigned rolls before the die that h
The second part of your explanation is correct. For the first part, this is what the MDN documentation says:

> This returned promise will resolve when all of the input's promises have resolved .... It rejects immediately upon any of the input promises rejecting ...

2021-11-25 15:11 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex5-pokerDiceChain.js
>        return results;
Correct!

2021-11-26 10:51 UTC, SaidYein commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +    console.og(msg);
You are right. I tested it, got the same error but somehow did not fix that. I fixed it now.

2021-11-26 10:52 UTC, SaidYein commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +  .catch((msg) => {
Fixed this too

2021-11-26 10:52 UTC, SaidYein commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +  return new Promise((res, rej) => {
Done

2021-11-26 10:53 UTC, SaidYein commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +function checkDoubleDigits(no) {
Got it and fixed it.

2021-11-26 11:16 UTC, SaidYein commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +            return;
I am not quite sure what to explain. Should I explain the error we get in the unmodified version, or why it works after the promise chain? I think you mean why it does not stop when the die goes off the table in the unmodified version. Anyways I did both :) If I am wrong, can you please explain yourself again?

2021-11-26 11:23 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +            return;
In both cases (callback version and promise version) the die should complete its scheduled rolls, even it falls off the table. That is what it says in the instructions. So you should **not** cut short its rolls by adding `return` after calling `reject`. Note that in practice you often will want to add a `return`, but in this exercise we want to see what happens when `resolve()` is called after `reject()` has been called earlier. Do you still see the `Success` message being printed when the die settles to its final value (as is the case in the callback version)? If not, why not?

2021-11-26 11:40 UTC, SaidYein commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +// Promise.all waits for the promise that take the longest time to be fulfilled. Thus, in case of rejection, rejected dies are still rolling until finishing their assigned rolls before the die that h
Yes, you are right. My understanding of async functions getting better day by day. I have changed my comment.

2021-11-26 12:11 UTC, SaidYein commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +            return;
Ok. I have to change my code. Because in this version, I went further than I was supposed to do. Now refactored it to continue to give values of dice after rejection. And explained what's going on.

2021-11-26 12:39 UTC, remarcmij approved these changes
Thanks @SaidYein for the changes. I'm now happy to approve your PR.

2021-11-29 14:30 UTC, remarcmij commented
Approved.

2021-11-29 14:30 UTC, closed without merging