Alexander said w1 Using APIs
HackYourHomework/Homework-class34 pull request #52
Opened 2021-11-22 14:41 UTC by AlexanderSaid

2021-11-23 17:27 UTC, remarcmij requested changes
Hi @AlexanderSaid, overall excellent work, all tests are passing. But see if you can sharpen up your explanations for ex3 and ex4.

2021-11-23 17:27 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +      } else {
Minor improvement: as you are checking that `firstName` is defined in line 15 it would make sense to postpone constructing the full name until after you have established that `firstName` is defined:

```suggestion
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (firstName) {
        const fullName = `${firstName} Doe`;
        resolve(fullName);
      } else {
```

2021-11-23 17:27 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +    }
Excellent explanatory comments and extra check for the type of the number. You can reduce the nesting a bit by "returning early" after detecting that the argument is not a number:

```suggestion
    if (typeof number !== 'number') {
      reject(new Error(`${number} is not a number`));
      return;
    }
    
    // check the number
    if (number >= 10 && number <= 99) {
      resolve('This is a double digit number!');
    } else {
      reject(new Error(`Expected a double digit number but got ${number}`));
    }
```

2021-11-23 17:27 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +        return;
Placing a `return` here (and also after `reject`) works fine. However, even without the `return` the die would stop rolling anyway because of the condition in line 37.

2021-11-23 17:27 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> + *  I'll leave it to the review discussion.
The callback version of the code may produce something like this:

```
Oops... Dice rolled off the table.
Dice value is now: 5
Success! Dice settled on 5.
```

So after a die is rolled off the table we still get a Success message some time later. If all is well the promise version does not produce a Success message for a die that rolled off the table. Why does the promise version not exhibit the same erroneous behaviour?

2021-11-23 17:27 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> + * I guess it's because Promise.all() wait all included promises to be resolved
Why doesn't a call to `reject()` stop a die from rolling (we touched upon this in the Q&A)?

2021-11-23 17:27 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex5-pokerDiceChain.js
>        return results;
Excellent!

2021-11-23 22:22 UTC, AlexanderSaid commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +      } else {
Agree, this makes more sense

2021-11-23 22:27 UTC, AlexanderSaid commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +    }
I need to remember using return more often this way

2021-11-26 22:58 UTC, AlexanderSaid commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> + *  I'll leave it to the review discussion.
I find it difficult to form my answer, what I can say that with using .then.catch when the promise settled it can be either fulfilled or rejected, so catching error will prevent resolved message.
But in callbacks the both results will be executed.

2021-11-26 23:06 UTC, AlexanderSaid commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> + * I guess it's because Promise.all() wait all included promises to be resolved
I didn't expect trying to explain it is this much hard.
So each promise in the array will settle to resolve or reject, and this won't effect the other promises results. And Promise.all when settle resolve an array of resolves or just give a reject if any of those promises is rejected, but it won't do this before it get the whole results from all promises.

2021-11-29 11:25 UTC, remarcmij requested changes
Hi @AlexanderSaid , with the info from the Q&A can you give it another try to improve your explanation of ex3 and ex4?

2021-11-29 11:25 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> + *  I'll leave it to the review discussion.
With the info from the Q&A, can you now improve your explanation?

2021-11-29 11:25 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> + * I guess it's because Promise.all() wait all included promises to be resolved
With the info from the Q&A, can you now improve your explanation?

2021-11-30 10:13 UTC, remarcmij commented
I was looking for your explanations in the code but you provided them in a GitHub comment which I overlooked. So all is fine and approved now and I will close your PR.

2021-11-30 10:14 UTC, remarcmij commented
Forgot to approve

2021-11-30 10:15 UTC, remarcmij approved these changes
Approved

2021-11-30 10:15 UTC, remarcmij commented
Approved

2021-11-30 10:15 UTC, closed without merging