Chris solution for API's homework Week 1
HackYourHomework/Homework-class34 pull request #53
Opened 2021-11-22 15:04 UTC by ChrisFayad

2021-11-24 15:37 UTC, jontra000 requested changes
Good work @ChrisFayad. Just a couple of small issues to clean up in the first two exercises.

2021-11-24 15:37 UTC, jontra000 commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +getAnonName('John');
Your code no longer logs the result of `getAnonName` to the console. Ideally we would like to see 'John Doe' get printed when we run the exercise.

2021-11-24 15:37 UTC, jontra000 commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +    }, 1000);
It's not necessary to use setTimeout here, the promise can just return immediately without a delay.

2021-11-24 15:37 UTC, jontra000 commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +// My Explanation
Great explanation! Very thorough

2021-11-25 11:38 UTC, ChrisFayad commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +    }, 1000);
I just thought it's a way to make the code go through some delay. Because right now we're still not working with API's!

2021-11-25 13:39 UTC, jontra000 commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +    }, 1000);
Well the question doesn't specify if you need a delay or not, so it doesn't matter too much in this case. As a general rule though, we should avoid adding any more complexity than we need to.

2021-11-25 13:40 UTC, jontra000 commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +getAnonName('John');
Still doesn't work I'm afraid. Make sure the message appears when you run `npm run it` for this exercise.

2021-11-26 12:10 UTC, jontra000 commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +getAnonName('John');
OK, two more things.

1. The original example would also log a message in the error case too, you should try and make your version behave the same way.

2. Putting the `console.log` call inside the `getAnonName` function works, but isn't quite what we're after in this case. The idea is to display the result of the promise to prove that you've implemented the promise correctly, but instead you're logging the intended result inside the promise. Take a look at how the result is printed in the other exercises if you're not sure what I'm getting at.

2021-11-27 10:07 UTC, ChrisFayad commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +getAnonName('John');
Sorry it took me awhile to get your point, but this time I think I fixed the issue :+1:

2021-11-27 13:51 UTC, jontra000 approved these changes
Yes, that's what I was after. Good work!

2021-11-30 13:25 UTC, closed without merging