Homework week 1 Caglar
HackYourHomework/Homework-class34 pull request #54
Opened 2021-11-22 22:57 UTC by caglar-kaya

2021-11-25 15:31 UTC, remarcmij requested changes
Hi @caglar-kaya, overall well done. There are some minor issues that I would like you to address.

2021-11-25 15:31 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +        return;
While it is generally a good practice to add a `return` here, the purpose of the exercise is to observe and explain what happens if you leave it out. (The instructions for this exercise say that the die should continue its scheduled rolls.) So please remove the `return` statement. The promise will then be rejected here but one or more rolls later `resolve` will be called. Will this resolve the promise that was rejected earlier? If not, why not? This is what you should explain in a comment.

2021-11-25 15:31 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +Promise.all(rollTheDices())
I think you made an improvement after I explained in slack that `rollTheDices` should return a single promise. However, since you now have a single promise at this point there is no point in using Promise.all again (you already used Promise.all in line 34). While this works all the same (Promise.all will happily work with a single input promise too) there is no justification to leave it in place here.

2021-11-25 15:31 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +they don't depend on each other.
Excellent explanation.

2021-11-25 15:31 UTC, remarcmij commented on 3-UsingAPIs/Week1/homework/ex5-pokerDiceChain.js
>        return results;
Correct.

2021-11-26 11:01 UTC, caglar-kaya commented
Hi @remarcmij 
Thank you for your review and giving your time to us.
I have edited ex3 and ex4 according to your comments.
Best regards..

2021-11-29 11:19 UTC, remarcmij approved these changes
Hi @caglar-kaya, thanks for these fixes. With those, I'm happy to approve your PR now.

2021-11-29 14:29 UTC, remarcmij commented
Approved.

2021-11-29 14:29 UTC, closed without merging