Ap is week1
HackYourHomework/Homework-class34 pull request #55
Opened 2021-11-23 12:25 UTC by Galalko

2021-11-27 17:16 UTC, yash-kapila requested changes
Hi Ahmed - I have finished reviewing the homework and have some suggestions. Could you please have a look?

2021-11-27 17:16 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +      reject(new Error("You didn't pass in a first name!"));
🆗

2021-11-27 17:16 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +    if (number >= 10 && number <= 99) {
🆗 but would be also a nice addition if you checked for `typeof number` being a `"number"`

2021-11-27 17:16 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +  });
I think you are missing the explanation part for the question asked.

```
Does the problem described above still occur? If not, what would be your explanation? Add your answer as a comment to be bottom of the file.
```

2021-11-27 17:16 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +  return Promise.all(mapingItems);
🆗

2021-11-27 17:16 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex5-pokerDiceChain.js
> +    })
🆗

2021-11-27 17:16 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> + */
That is right. I would still recommend to read this page again https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all especially the part `Promise.all() will reject immediately upon any of the input promises rejecting. In comparison, the promise returned by Promise.allSettled() will wait for all input promises to complete, regardless of whether or not one rejects. Consequently, it will always return the final result of every promise and function from the input iterable.`

2021-11-29 20:26 UTC, Galalko commented
Thanks @yash-kapila for your time

2021-11-29 20:27 UTC, Galalko commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +      reject(new Error("You didn't pass in a first name!"));
Thanks

2021-11-29 20:31 UTC, Galalko commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +  return Promise.all(mapingItems);
Thanks 🌷

2021-11-29 20:31 UTC, Galalko commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +  });
Thanks i wrote a comment .

2021-12-12 11:41 UTC, yash-kapila approved these changes

2021-12-12 11:42 UTC, closed without merging