Api week1 updated
HackYourHomework/Homework-class34 pull request #64
Opened 2021-11-24 17:09 UTC by Danielboi886

Somehow my main is a total mess (just like my life). I reverted all changes and roll back to the first commit. Sorry for all the fuss but apart from my ex1 from Browser week1, the rest is my homework! 

Thank you for reviewing my homework and I'll correct it on time! 

Daniel ! ;-)

2021-11-27 16:45 UTC, yash-kapila requested changes
Hi @Danielboi886 - I have finished reviewing the homework but have some comments to address. Could you please look?

2021-11-27 16:45 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +  return lastNamePromise;
👍

2021-11-27 16:45 UTC, yash-kapila commented on 1-JavaScript/Week3/homework/ex1-giveCompliment.js
> +    'awesome ',
Hi @Danielboi886 - I don't think that this file belongs to "Using APIs - Week 1" homework. Can you please check? 🙂

2021-11-27 16:45 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +  return numberPromise;
Logic is good but you could also have an additional check here to make sure that the `typeof number` is always a `"number"` and not something else 🙂

2021-11-27 16:45 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +**/
Hi @Danielboi886 - are you sure that the code with promises is working the same way as with callbacks?

I executed your code and this is what I see in response

```
Dice scheduled for 10 rolls...
Dice value is now: 3
Dice value is now: 3
Dice value is now: 4
Dice value is now: 6
Dice value is now: 1
Dice value is now: 4
Dice value is now: 1
Error: Oops... Dice rolled off the table.
    at rollOnce (index.js:11:16)
    at Timeout._onTimeout (index.js:19:26)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Dice value is now: 2
Dice value is now: 4
Dice value is now: 4
```

There is a small difference that the dice is not being settled as it was in callbacks even after it rolled back i.e we have a single error and no "success" anymore.

It doesn't have to do with setTimeout but with how `resolve` and `reject` callbacks work together. Can you check?

2021-11-27 16:45 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +  **/
Hi @Danielboi886 - the logic is right but the explanation is not quite accurate. I will recommend having a look here and see if it makes sense - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

```
Promise.all() will reject immediately upon any of the input promises rejecting. In comparison, the promise returned by Promise.allSettled() will wait for all input promises to complete, regardless of whether or not one rejects. Consequently, it will always return the final result of every promise and function from the input iterable.
```

2021-11-27 16:45 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex5-pokerDiceChain.js
> +    })
🆗

2021-12-12 11:36 UTC, yash-kapila approved these changes

2021-12-12 11:37 UTC, closed without merging

2021-12-14 23:29 UTC, Danielboi886 commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +**/
Hi! A few weeks passed and I definitely got a better understanding of promise. Now I got what you mean! So in my improved code, when the promise is rejected it will log a single line saying "the dice rolled off" instead of throwing an error. Also, when a promise is rejected it is *rejected*, and that will be the final status of a promise. So situations like callbacks (e.g. log a failure and then log a success) would not happen in promises.  
My updated code: 
https://playcode.io/844183/