APIs-Week-1
HackYourHomework/Homework-class34 pull request #65
Opened 2021-11-26 10:23 UTC by Mustafa681

2021-11-27 17:09 UTC, yash-kapila requested changes
Hi @Mustafa681 - I have reviewed the homework and have a couple small comments to be addressed. Can you please have a look?

2021-11-27 17:09 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +    }, 1000);
🆗

2021-11-27 17:09 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +    if (number >= 10 && number <= 99) {
🆗 but you can have an additional check here to make sure that `typeof number` is a `"number"` and not anything else

2021-11-27 17:09 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +//  using promise solved the problem practically. either resolved or  or rejected
Hi @Mustafa681 - I don't think that explanation you provided explains quite clearly what is asked i.e`Does the problem described above still occur? If not, what would be your explanation? Add your answer as a comment to be bottom of the file.`

Which means that like in callbacks, once you have rejected the promise(an error occurs), do you still see the resolve method invoked(success call back executed?)

2021-11-27 17:09 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex5-pokerDiceChain.js
> +    .then((value) => {
🆗

2021-11-27 17:09 UTC, yash-kapila commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +// there's not return statement in the rejection rollDice
Hi @Mustafa681 - although a return statement in rollDice method would fix the issue but that is not what we are looking for in the explanation. I will recommend having a look here and see if it makes sense - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

```
Promise.all() will reject immediately upon any of the input promises rejecting. In comparison, the promise returned by Promise.allSettled() will wait for all input promises to complete, regardless of whether or not one rejects. Consequently, it will always return the final result of every promise and function from the input iterable.
```

2021-11-30 18:34 UTC, Mustafa681 commented on 3-UsingAPIs/Week1/homework/ex3-rollDice.js
> +//  using promise solved the problem practically. either resolved or  or rejected
Hi @yash-kapila , Thank you for reviewing my homework and sorry for my late response, 
you're totally right about that,  I've had some issues with branches and I got confused for a while, then I've decided to do everything again and forgot to update my Explanations. 

 
So once a resolve or reject is called, the state of promise will be settled to either 
resolved or rejected and the rest of the calls will be ignored.

2021-11-30 18:59 UTC, Mustafa681 commented on 3-UsingAPIs/Week1/homework/ex4-pokerDiceAll.js
> +// there's not return statement in the rejection rollDice
Hi @yash-kapila, Thank you for your time,

Here we did pass an array of promises to Promise.all() function. and all promises were executed asynchronously, with no dependency!
so in this case when we get a rejection, the dices that did not
finish their roll will continue to do so. cuz as I said before no dependency.

2021-12-12 11:36 UTC, yash-kapila approved these changes

2021-12-12 11:36 UTC, closed without merging