Homework week 2 Danijel Cvitkusic
HackYourHomework/Homework-class34 pull request #71
Opened 2021-11-30 10:11 UTC by DanijelCvit

2021-12-01 12:35 UTC, jontra000 requested changes
Looks good @DanijelCvit. Just the bug in ex2 to fix and then I can approve.

2021-12-01 12:35 UTC, jontra000 commented on 3-UsingAPIs/Week2/homework/ex5-vscDebug.js
> +    console.log(err.stack);
Don't forget to delete the stack log!

2021-12-01 13:32 UTC, DanijelCvit commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +    .then((jsonData) => {
Thanks.Removed.

2021-12-01 13:32 UTC, DanijelCvit commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> -function fetchData(/* TODO parameter(s) go here */) {
Ah yes. Fixed it :)

2021-12-02 12:07 UTC, jontra000 commented
Looks good! Approved.

2021-12-02 12:07 UTC, closed without merging