Homework week 2 Caglar
HackYourHomework/Homework-class34 pull request #72
Opened 2021-11-30 10:54 UTC by caglar-kaya

Hi @remarcmij ,
I have finished my homework for week2.
Best regards.

2021-12-02 13:11 UTC, remarcmij requested changes
Hi Caglar, good work! There are some issues though with the pokemon exercise despite the fact that it seems to work okay. Please have a look at my comments and try to fix the issues.

2021-12-02 13:11 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +        fetchAndPopulatePokemons();
This will prevent the list to be populated more than once. However, the user will still be able to click the button (which seems to have no effect). A better approach is to simply add the  `disabled` attribute to the button once it has been clicked the first time. This will gray out the button and disable the click event to be fired. The user now has a visual clue that the button can no longer be used.

2021-12-02 13:11 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex3-rollAnAce.js
>  }
👍

2021-12-02 13:11 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex4-diceRace.js
> +  });
```suggestion
  const promises = dices.map(rollDice);
```

This will do the same but in a more concise way.

2021-12-02 13:11 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex4-diceRace.js
> + * we get only resolve value or reject reason of first dice that resolves or rejects.
Excellent explanation.

2021-12-03 12:21 UTC, caglar-kaya commented
Hi @remarcmij 
I have applied your comments.
Best regards.

2021-12-03 12:51 UTC, remarcmij requested changes
Hi Caglar, thanks for the updates. I have still found a minor issue with updating the image rather than adding a new one each time the selection is changed. After you have fixed that I will be happy to approve your PR.

2021-12-03 12:51 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +
This blank line should have been removed automatically by Prettier. Are you sure your Prettier setup in VSCode working?

2021-12-03 12:51 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    const image = document.createElement('img');
The instruction says you should update the image rather than add a new one each time the selection is changed.

2021-12-03 12:51 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    const selector = document.querySelector('select');
There is no need for this variable. It is the same as `select` from line 43.

2021-12-05 20:02 UTC, caglar-kaya commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +
Hi @remarcmij,
I checked settings.json file in my homework folder and it has `"editor.defaultFormatter": "esbenp.prettier-vscode",` this line. I think Prettier doesn't remove blank lines.

2021-12-05 20:30 UTC, caglar-kaya commented
Hi @remarcmij ,
I applied your comments.
Best regards.

2021-12-05 20:52 UTC, remarcmij approved these changes
Hi @caglar-kaya, thanks for these final updates. I'm now happy to approve your PR. Nevertheless, I have added some minor suggestions for your consideration.

2021-12-05 20:52 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    const image = document.createElement('img');
This alternative would work too. Instead of removing an existing `<img>` you could just reuse it.

```suggestion
    let image =  document.querySelector('img');
    if (!image) {
       image = document.createElement('img');
       document.body.appendChild(image);
    }
```

2021-12-05 20:52 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    document.body.appendChild(image);
Of course, this line would then have to go.

```suggestion
```

2021-12-05 20:52 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    console.log(error.message);
How many times do you want this error being logged in the console? You are also logging it in the catch block of the calling functions.

2021-12-05 20:53 UTC, remarcmij commented
Approved.

2021-12-05 20:53 UTC, closed without merging