Said yein w2 using ap is
HackYourHomework/Homework-class34 pull request #73
Opened 2021-11-30 12:40 UTC by SaidYein

2021-12-02 15:58 UTC, remarcmij requested changes
Hi @SaidYein, all exercises except for the pokemon one are fine. I think you also grasped the concept of error handling well, but the pokemon code organisation should be improved. Please check my comments below and see if you can fix the issues.

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +  return fetch(url).then((response) => {
You can mix `.then()` and `async/await` in a single a code base, but some developers (I'm not necessarily one of them) would insist on consistency (one or the other). In the case, I have no issue: this code is more concise.

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +    }
```suggestion
    if (response.ok) {
      return response.json();
    }
    throw new Error('Request failed!');
```

... well, it would be more concise if you left out the unnecessary `else`. After the `return` there is no need for it.

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +  const errorDiv = document.createElement('h1');
This is not a 'div', is it? It looks like an 'h1' to me.

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
>  window.addEventListener('load', main);
Work well 👍

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    if (!response.ok) throw new Error('Data request failed!');
It is a best practice to always use curly braces, even if there is only one statement to go inside.

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +async function fetchAndPopulatePokemons(jsonResponse) {
As the name implies, this function should do the fetching and not the function `main()`.  It should fetch the data on demand when the button is clicked.

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  document.body.style.flexDirection = 'column';
Best to put all styling in a separate CSS file and just add CSS class name attributes in JavaScript.

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    option.textContent = pokemon.name;
You can also assign the pokemon url to the `option.value` attribute for use later:

```js
option.value = pokemon.url;
```

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    const selectedUrl = `https://pokeapi.co/api/v2/pokemon/${event.target.value}`;
You should not make assumptions on how the url for the pokemon image should be constructed. The API owner may change the format of that url in the future. Instead, the owner provides a ready-made url in the pokemon data (the one I recommended to assign to `option.value`, which is more future-proof and should be used here.

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  };
Here I would say that you should use `async/await` for consistency.

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  image.style.width = '164px';
Styling can go to a separate CSS file.

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +window.addEventListener('load', main);
Where is the button that the user should press to get the pokemons?

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex3-rollAnAce.js
>  main();
👍

2021-12-02 15:58 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex4-diceRace.js
>  main();
👍

2021-12-02 16:03 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  const endpoint = `https://pokeapi.co/api/v2/pokemon?limit=10'/`;
Forgot to mention, why the extra quote and slash at the end of this url?

2021-12-04 11:23 UTC, SaidYein commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  const endpoint = `https://pokeapi.co/api/v2/pokemon?limit=10'/`;
Don't really know :) fixed it!

2021-12-04 11:53 UTC, SaidYein commented
I have changed the code according to your suggestions. And I have realized that I am not focusing on writing more readable code enough. But I am working on it :) thanks for the suggestions

For Pokemon exercise, I have used the fetchData() in both fetchAndPopulatePokemons() and fetchImage() functions. I catch the errors in both function and finally in the main(). 

The only thing left that bothers me is that I called fetchImage() function in fetchAndPopulatePokemons() and did not chain in main(). If you want me to fix it, I can give it a try.

2021-12-04 12:24 UTC, remarcmij requested changes
Hi @SaidYein, thanks for the improvements. I have still found opportunities for further improvements. Can you have a look at my latest comments?

2021-12-04 12:24 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.html
> +  <button type="button" class="getPokeButton">Get Pokemon!</button>
You were expected to create this button in JavaScript, for instance, in the `main()` function.  You can add the click event handler there too.

2021-12-04 12:24 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    };
This will work but I would suggest a different method of replacing the image. See my comment for `fetchImage()` below.

2021-12-04 12:24 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    const image = document.createElement('img');
Reuse the image element if it already exists

```suggestion
    // check for an existing image 
    let image = document.querySelector('img');
    // if it does not exist, create a new one
    if (!image) {
        image = document.createElement('img');
        document.body.appendChild(image);
     }
```

2021-12-04 12:24 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    document.body.appendChild(image);
```suggestion
```

2021-12-04 12:24 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    fetchAndPopulatePokemons();
You can create the button here in `main()` and add a `click` event handler to call `fetchAndPopulatePokemons()`. Make sure that the user can click the button once only, for instance, by adding the `disabled` attribute to the button after is has been clicked.

You don't need a `try/catch` block in `main`, because there are no errors to catch. They are all handled elsewhere.

Also `main` does need the `async` keyword because inside the function you are not using `await`.

2021-12-04 12:24 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +getButton.addEventListener('click', main);
This code does not need to be at the global level. Move it inside `main` so that it gets executed when the browser has finished loading the page.

```suggestion
```

2021-12-06 10:51 UTC, remarcmij approved these changes
Hi @SaidYein, thanks for these final updates. All is well now and I'm approving and closing your  PR.

2021-12-06 10:51 UTC, remarcmij commented
Approved

2021-12-06 10:51 UTC, closed without merging