Alexander said w2 Using APIs
HackYourHomework/Homework-class34 pull request #74
Opened 2021-11-30 16:39 UTC by AlexanderSaid

@remarcmij 
Hi Jim, 
This is my homework :)

2021-12-02 17:36 UTC, remarcmij requested changes
Hi @AlexanderSaid, overall this looks good. But there are still some issues in the pokemon app as well as minor issues elsewhere. Please see if you can fix these.

2021-12-02 17:36 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  return jsonResponse;
```suggestion
  return response.json();
```

No need to `await` here because you are not processing the result of `response.json()` here. You can just return the promise from `response.json()` directly.

You are right to not catch the error here but to let it propagate to the calling functions where it can be dealt with.

2021-12-02 17:36 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +      option.value = pokemon.name;
```suggestion
      option.value = pokemon.url;
```

Each pokemon object has a `url` property that can be used to fetch the image. This is the url you should actually use. By assigning it to the `option.value` attribute you can pick it up later to fetch the image in the `change` event handler.

2021-12-02 17:36 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    getButton.setAttribute('disabled', 'disabled');
We discussed this one. Best to give a visual clue to the user that the button is not functional anymore, by disabling it.

2021-12-02 17:36 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    const url = `${URL}${e.target.value}`;
You should not make any assumptions on how to construct a url for fetching the image. The API provider has given you a url in the pokemon data object for fthat purpose. The API provider may change the precise url format in the future but in that case can be expected to give you an update url in the pokemon object. So using the provided url is more future-proof. If you save the provided url in `option.value` then `e.target.value` will be that url.

2021-12-02 17:36 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  getButton.addEventListener('click', renderSelectList);
This name `getButton` is slightly confusing because verb-based names indicate action and therefore are expected to represent functions (e.g. a function to get a button). Since there is only one button in the entire application you could simply call it `button` to avoid confusion.

2021-12-03 01:05 UTC, AlexanderSaid commented on 3-UsingAPIs/Week2/homework/ex1-programmerFun/index.js
> +    .catch((error) => console.log(error.message));
Yes you're right, I committed it before sunday session and forgot to check it again

2021-12-03 02:32 UTC, AlexanderSaid commented
Hi @remarcmij, 
I made the changes you suggested and some other changes, hoping it's more valid now.

2021-12-03 13:57 UTC, remarcmij requested changes
Hi @AlexanderSaid, thanks for the updates. Much improved already. But there are still some changes I would like you to make. Please have a look at my comments.

2021-12-03 13:57 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +    console.log(response);
Take out no longer needed console.logs from finished code.

2021-12-03 13:57 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +async function errorHandler(error) {
This is not an async function. There is no `await` inside.

2021-12-03 13:57 UTC, remarcmij commented on 3-UsingAPIs/Week2/homework/ex2-pokemonApp/index.js
> +  await fetchAndPopulatePokemons(URL);
If you fetch on demand when the user presses the button, the `fetchAndPopulatePokemons()` function does not need to be async. Instead, the click event handler inside `fetchAnd...` needs to be async then.  Consequently, you would not need the `await` here nor the `async` keyword in line 121.

2021-12-08 13:50 UTC, remarcmij approved these changes
Hi @AlexanderSaid, all is well now. I'm approving your PR.

2021-12-08 13:50 UTC, remarcmij commented
Approved

2021-12-08 13:50 UTC, closed without merging