Osama bazbooz- APIs - Week2 - Homework
HackYourHomework/Homework-class34 pull request #78
Opened 2021-11-30 18:18 UTC by obazbooz

2021-12-01 11:39 UTC, jontra000 requested changes
Hi @obazbooz. Exercises 1, 4, 5 and 6 all look good. There are just a few things to fix in exercises 2 and 3.

2021-12-01 12:37 UTC, jontra000 commented
I also noticed that when you press the 'Get Pokemon' button more than once the selector gets filled with multiple copies of the list. Could you fix this too please?

2021-12-01 16:19 UTC, obazbooz commented
Dear @jontra000,

Thanks a lot for your valuable feedback on my homework.
I have fixed all the bugs you mentioned, it will be nice if you give me your feedback about the final result.

Best regards,
Osama

2021-12-02 12:02 UTC, jontra000 requested changes
Good work fixing the bug. Could you address my two comments and then I can close the PR. Do let me know if you need any help

2021-12-02 12:02 UTC, jontra000 commented on 3-UsingAPIs/Week2/homework/ex3-rollAnAce.js
> +    while (rollDiceResponse !== wantedValue) {
Notice how now the conditions in the if statements are just the negative of what is in the while statement, this means that the if statements are redundant and we can remove them and make this code a lot simpler.

2021-12-04 14:45 UTC, obazbooz commented
Dear @jontra000 ,

Thanks for your feedback, I have worked on the notes and fixed the fetch to be on click in ex2. Also I correct the if conditions statements bug in ex3. 
So hopefully it works well now  :D 
I will be happy to know your feedback about my fixing.

Best regards,
Osama

2021-12-05 11:51 UTC, jontra000 commented
Nice work @obazbooz. Everything looks good now

2021-12-05 11:51 UTC, closed without merging